"""add image_url to anime table

Revision ID: 96531baac18e
Revises: 44bd48205e9d
Create Date: 2024-03-09 21:12:15.879099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96531baac18e'
down_revision: Union[str, None] = '44bd48205e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'image_url')
    # ### end Alembic commands ###
