"""fixed sequence in comment table

Revision ID: 44bd48205e9d
Revises: 6fba9a8e112b
Create Date: 2024-02-18 23:09:13.898030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44bd48205e9d'
down_revision: Union[str, None] = '6fba9a8e112b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
