"""add email column to user

Revision ID: a8ce31610050
Revises: 1ce4677246e1
Create Date: 2024-02-07 22:24:24.733382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8ce31610050'
down_revision: Union[str, None] = '1ce4677246e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq_user_email'), 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_email'), 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
