"""add comment table

Revision ID: 600216a43868
Revises: a8ce31610050
Create Date: 2024-02-14 21:45:26.963991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600216a43868'
down_revision: Union[str, None] = 'a8ce31610050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_anime', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_anime'], ['anime.mal_id'], name=op.f('fk_comment_id_anime_anime')),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name=op.f('fk_comment_id_user_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
