"""empty message

Revision ID: 4658369055a4
Revises: 96531baac18e
Create Date: 2024-03-11 20:55:06.464666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4658369055a4'
down_revision: Union[str, None] = '96531baac18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_anime', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_anime', 'status')
    # ### end Alembic commands ###
