"""anime_genre table

Revision ID: 06142cb2d0cf
Revises: 381937dc74e5
Create Date: 2023-08-30 12:44:27.862613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06142cb2d0cf'
down_revision = '381937dc74e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_anime', sa.Integer(), nullable=False),
    sa.Column('id_genre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_anime'], ['anime.mal_id'], ),
    sa.ForeignKeyConstraint(['id_genre'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime_genre')
    # ### end Alembic commands ###
