"""initial

Revision ID: 1d48172418a7
Revises: 
Create Date: 2023-09-04 21:53:33.462084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d48172418a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'title_english',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('anime', 'episodes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('anime', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('anime', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('anime', 'rating',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('anime', 'synopsis',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('anime', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('anime', 'members',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'members',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('anime', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('anime', 'synopsis',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('anime', 'rating',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('anime', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('anime', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('anime', 'episodes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('anime', 'title_english',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
