"""empty message

Revision ID: 381937dc74e5
Revises: d3a7e010be66
Create Date: 2023-08-29 21:47:11.604605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381937dc74e5'
down_revision = 'd3a7e010be66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studio')
    # ### end Alembic commands ###
