"""anime_studio

Revision ID: 9929849073ca
Revises: 06142cb2d0cf
Create Date: 2023-08-30 13:00:33.386517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9929849073ca'
down_revision = '06142cb2d0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_studio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_anime', sa.Integer(), nullable=False),
    sa.Column('id_studio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_anime'], ['anime.mal_id'], ),
    sa.ForeignKeyConstraint(['id_studio'], ['studio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime_studio')
    # ### end Alembic commands ###
